/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Hajer1
 */
import service.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import java.util.List;

public class EditCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form EditCoursePanel
     */
    private String courseId;
    private String instructorId;
    private InstructorDashboardFrame parent;
    private CourseService courseService;
    private DefaultTableModel lessonsTableModel;
    private String selectedLessonId;

    public EditCoursePanel() {
        initComponents();
        this.courseService = new CourseService();
        initializeLessonsTable();
    }

    public EditCoursePanel(String instructorId, String courseId, InstructorDashboardFrame parent) {
        initComponents();
        this.courseId = courseId;
        this.parent = parent;
        this.instructorId = instructorId;
        this.courseService = new CourseService();
        initializeLessonsTable();
        loadCourseData();
        loadLessonsToTable();
    }

    private void initializeLessonsTable() {

        lessonsTableModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Title", "Resources"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        lessonsTable.setModel(lessonsTableModel);

        lessonsTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && lessonsTable.getSelectedRow() != -1) {
                loadSelectedLessonData();
            }
        });
    }

    private void loadCourseData() {
        if (courseId != null) {
            Course course = courseService.getCourseById(courseId);
            if (course != null) {
                courseTitleField.setText(course.getCourseTitle());
                courseDescriptionField.setText(course.getCourseDescription());
            } else {
                JOptionPane.showMessageDialog(this,
                        "Course not found!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    protected void loadLessonsToTable() {
        if (courseId == null) {
            return;
        }

        // Clear existing data
        lessonsTableModel.setRowCount(0);

        // Get lessons for the current course
        Course course = courseService.getCourseFromInstance(courseId);
        if (course != null) {
            List<Lesson> lessons = course.getLessons();

            for (Lesson lesson : lessons) {
                String resources = courseService.getResourcesAsCommaSeparated(lesson);
                lessonsTableModel.addRow(new Object[]{
                    lesson.getLessonId(),
                    lesson.getLessonTitle(),
                    resources
                });
            }

            // Show message if no lessons found
            if (lessons.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No lessons found for this course.",
                        "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }

        clearLessonFields();
    }

    protected void loadSelectedLessonData() {
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow >= 0) {
            // Get the lesson ID from the selected row
            selectedLessonId = (String) lessonsTableModel.getValueAt(selectedRow, 0);
            String lessonTitle = (String) lessonsTableModel.getValueAt(selectedRow, 1);
            String resources = (String) lessonsTableModel.getValueAt(selectedRow, 2);

            // Load data into editing fields
            lessonTitleField.setText(lessonTitle);
        }
    }

    private void clearLessonFields() {
        lessonTitleField.setText("");
        selectedLessonId = null;
    }

    public void setCourseToEdit(String courseId) {
        this.courseId = courseId;
        loadCourseData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        returnToMenuButton = new javax.swing.JButton();
        saveProgressButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        courseTitleField = new javax.swing.JTextField();
        lessonTitleField = new javax.swing.JTextField();
        courseDescriptionField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteLessonButton = new javax.swing.JButton();
        addLessonButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));

        jLabel1.setBackground(new java.awt.Color(252, 250, 247));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Course");

        returnToMenuButton.setBackground(new java.awt.Color(230, 240, 250));
        returnToMenuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        returnToMenuButton.setForeground(new java.awt.Color(0, 30, 80));
        returnToMenuButton.setText("Return To Menu");
        returnToMenuButton.setFocusPainted(false);
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        saveProgressButton.setBackground(new java.awt.Color(230, 240, 250));
        saveProgressButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        saveProgressButton.setForeground(new java.awt.Color(0, 30, 80));
        saveProgressButton.setText("Save Progress");
        saveProgressButton.setFocusPainted(false);
        saveProgressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProgressButtonActionPerformed(evt);
            }
        });

        lessonsTable.setBackground(new java.awt.Color(230, 240, 250));
        lessonsTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lessonsTable.setForeground(new java.awt.Color(0, 30, 80));
        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Title", "Resources"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        jLabel2.setBackground(new java.awt.Color(252, 250, 247));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 30, 80));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lessons");

        jLabel3.setBackground(new java.awt.Color(252, 250, 247));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 30, 80));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lesson Title :");

        courseTitleField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        courseTitleField.setForeground(new java.awt.Color(0, 30, 80));

        lessonTitleField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lessonTitleField.setForeground(new java.awt.Color(0, 30, 80));

        courseDescriptionField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        courseDescriptionField.setForeground(new java.awt.Color(0, 30, 80));

        jLabel5.setBackground(new java.awt.Color(252, 250, 247));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 30, 80));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Course Title :");

        jLabel6.setBackground(new java.awt.Color(252, 250, 247));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 30, 80));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Course Description :");

        deleteLessonButton.setBackground(new java.awt.Color(230, 240, 250));
        deleteLessonButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        deleteLessonButton.setForeground(new java.awt.Color(120, 0, 0));
        deleteLessonButton.setText("Delete Lesson");
        deleteLessonButton.setFocusPainted(false);
        deleteLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonButtonActionPerformed(evt);
            }
        });

        addLessonButton.setBackground(new java.awt.Color(230, 240, 250));
        addLessonButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        addLessonButton.setForeground(new java.awt.Color(0, 30, 80));
        addLessonButton.setText("Add Lesson");
        addLessonButton.setFocusPainted(false);
        addLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(230, 240, 250));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 30, 80));
        jButton1.setText("Add Quiz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lessonTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(199, 199, 199))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(saveProgressButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteLessonButton)
                        .addGap(18, 18, 18)
                        .addComponent(addLessonButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(returnToMenuButton)
                        .addGap(134, 134, 134))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(courseTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(courseDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lessonTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveProgressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }

        // Show the parent dashboard and refresh courses
        if (parent != null) {
            parent.setVisible(true);
            parent.loadCoursesToTable();
        }
    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    private void saveProgressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProgressButtonActionPerformed
        boolean courseUpdated = false;
        boolean lessonUpdated = false;
        boolean hasErrors = false;
        String newCourseTitle = courseTitleField.getText().trim();
        String newCourseDescription = courseDescriptionField.getText().trim();

        if (newCourseTitle.isEmpty() || newCourseDescription.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in both course title and description.",
                    "Input Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            courseUpdated = courseService.editCourse(courseId, newCourseTitle, newCourseDescription);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error updating course: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            hasErrors = true;
        }
        if (selectedLessonId != null) {
            String newLessonTitle = lessonTitleField.getText().trim();

            if (!newLessonTitle.isEmpty()) {
                try {
                    lessonUpdated = courseService.editLesson(courseId, selectedLessonId, newLessonTitle);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Error updating lesson: " + e.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                    hasErrors = true;
                }
            }
        }
        
        if (!hasErrors) {
            if (courseUpdated && lessonUpdated) {
                JOptionPane.showMessageDialog(this,
                        "Course and lesson updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            } else if (courseUpdated) {
                JOptionPane.showMessageDialog(this,
                        "Course updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            } else if (lessonUpdated) {
                JOptionPane.showMessageDialog(this,
                        "Lesson updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "No changes were made.",
                        "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Some updates failed. Please check the error messages above.",
                    "Partial Success",
                    JOptionPane.WARNING_MESSAGE);
        }
        //load new data to course table
        if (courseUpdated || lessonUpdated) {
            loadLessonsToTable();
            if (parent != null) {
                parent.loadCoursesToTable();
            }
        }
    }//GEN-LAST:event_saveProgressButtonActionPerformed

    private void deleteLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLessonButtonActionPerformed
        if (selectedLessonId == null) {
            JOptionPane.showMessageDialog(this,
                    "Please select a lesson from the table first.",
                    "No Lesson Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this lesson?\nThis action cannot be undone.",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean success = courseService.deleteLesson(courseId, selectedLessonId);
                if (success) {
                    JOptionPane.showMessageDialog(this,
                            "Lesson deleted successfully!",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    // Refresh the table and clear fields
                    loadLessonsToTable();
                    clearLessonFields();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Failed to delete lesson.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error deleting lesson: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteLessonButtonActionPerformed

    private void addLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonButtonActionPerformed
        AddLessonFrame addLessonFrame = new AddLessonFrame(courseId, this);
        addLessonFrame.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_addLessonButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            if (selectedLessonId == null) {
        JOptionPane.showMessageDialog(this,
                "Please select a lesson from the table first.",
                "No Lesson Selected",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get the selected lesson title for display
    int selectedRow = lessonsTable.getSelectedRow();
    String lessonTitle = (String) lessonsTableModel.getValueAt(selectedRow, 1);
    
    // Create and show AddQuizFrame - PASS THE PARENT FRAME AND IDS
    AddQuizFrame addQuizFrame = new AddQuizFrame(instructorId, courseId, selectedLessonId, parent);
    addQuizFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLessonButton;
    private javax.swing.JTextField courseDescriptionField;
    private javax.swing.JTextField courseTitleField;
    private javax.swing.JButton deleteLessonButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lessonTitleField;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JButton returnToMenuButton;
    private javax.swing.JButton saveProgressButton;
    // End of variables declaration//GEN-END:variables
}
