/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Hajer1
 */
import model.*;
import service.*;
import java.util.*;


public class MyCertificatesFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyCertificatesFrame
     */
    private String studentId;
    private StudentDashboardFrame parent;

    public MyCertificatesFrame() {
        initComponents();
    }

    public MyCertificatesFrame(String studentId, StudentDashboardFrame parent) {
        initComponents();
        this.studentId = studentId;
        this.parent = parent;
        loadCertificates();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        returnToMenuButton = new javax.swing.JButton();
        viewCertificateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));

        jTable1.setBackground(new java.awt.Color(230, 240, 250));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 30, 80));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Course Name", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(252, 250, 247));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("☆ My Certificates ☆");

        returnToMenuButton.setBackground(new java.awt.Color(230, 240, 250));
        returnToMenuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        returnToMenuButton.setForeground(new java.awt.Color(0, 30, 80));
        returnToMenuButton.setText("Return To Menu");
        returnToMenuButton.setFocusPainted(false);
        returnToMenuButton.setMinimumSize(new java.awt.Dimension(251, 32));
        returnToMenuButton.setPreferredSize(new java.awt.Dimension(251, 32));
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        viewCertificateButton.setBackground(new java.awt.Color(230, 240, 250));
        viewCertificateButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        viewCertificateButton.setForeground(new java.awt.Color(0, 30, 80));
        viewCertificateButton.setText("View Certificate");
        viewCertificateButton.setFocusPainted(false);
        viewCertificateButton.setMinimumSize(new java.awt.Dimension(251, 32));
        viewCertificateButton.setPreferredSize(new java.awt.Dimension(251, 32));
        viewCertificateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCertificateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewCertificateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCertificateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
        if (parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    private void viewCertificateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCertificateButtonActionPerformed
    
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a certificate to view.",
                    "No Certificate Selected",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Get certificate ID from the selected row (column 0)
            String certificateId = jTable1.getValueAt(selectedRow, 0).toString();

            // Open the ViewCertificate frame
            ViewCertificate viewCertFrame = new ViewCertificate(certificateId, studentId, this);
            viewCertFrame.setVisible(true);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error opening certificate: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_viewCertificateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void loadCertificates() {
    try {
        // Get certificate service
        CertificateService certService = new CertificateService();

        // Get student's certificates
        List<Certificate> certificates = certService.getStudentCertificates(studentId);

        // Create table model
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Certificate ID", "Course Name", "Issue Date"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table non-editable
            }
        };

        // Populate table with certificate data
        for (Certificate cert : certificates) {
            // Format the date nicely
            String formattedDate = new java.text.SimpleDateFormat("MMM dd, yyyy").format(cert.getIssueDate());

            // Add row to table
            model.addRow(new Object[]{
                cert.getCertificateId(),
                cert.getCourseName(),
                formattedDate
            });
        }

        // Set the model to the table
        jTable1.setModel(model);

        // Adjust column widths
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120); // ID column
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300); // Course name
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100); // Date

        // Show message if no certificates
        if (certificates.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "You haven't earned any certificates yet.\nComplete courses to earn certificates!",
                    "No Certificates",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Error loading certificates: " + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}

    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MyCertificatesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MyCertificatesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MyCertificatesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MyCertificatesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MyCertificatesFrame().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton returnToMenuButton;
    private javax.swing.JButton viewCertificateButton;
    // End of variables declaration//GEN-END:variables
}
