/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Hajer1
 */
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import service.*;


public class ViewCourseDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewCourseDetailsFrame
     */
    private Course course;
    private String studentId;
    private ViewEnrolledCoursesFrame parent;
    private DefaultTableModel lessonsTableModel;
    private StudentService studentService;
    private AuthService authService;

    public ViewCourseDetailsFrame() {
        initComponents();
    }

    public ViewCourseDetailsFrame(String studentId, Course course, ViewEnrolledCoursesFrame parent) {
        initComponents();
        this.course = course;
        this.studentId = studentId;
        this.parent = parent;
        loadLessonsToTable();
    }

    protected void loadLessonsToTable() {
        if (course == null) {
            JOptionPane.showMessageDialog(this,
                    "No course selected.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (lessonsTableModel == null) {
            lessonsTableModel = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{"Content", "Lesson ID", "Lesson Title", "Completed", "Resources"}
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make table non-editable
                }
            };
            lessonsTable.setModel(lessonsTableModel);
        }

        lessonsTableModel.setRowCount(0);

        CourseService courseService = new CourseService();
        studentService = new StudentService();
        List<Lesson> lessons = course.getLessons();

        if (lessons == null || lessons.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No lessons found for this course.",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Get the current student to check completion status
        AuthService authService = new AuthService();
        Student student = (Student) authService.getUserById(studentId);

        for (Lesson lesson : lessons) {
            String resources = courseService.getResourcesAsCommaSeparated(lesson);

            boolean isCompleted = false;
            if (student != null) {
                List<String> completedLessons = student.getCompletedLessons(course.getCourseId());
                isCompleted = completedLessons != null && completedLessons.contains(lesson.getLessonId());
            }

            lessonsTableModel.addRow(new Object[]{
                lesson.getContent(),
                lesson.getLessonId(),
                lesson.getLessonTitle(),
                isCompleted ? "Yes" : "No",
                resources
            });
        }

        // Refresh the table
        lessonsTableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        returnToMenuButton = new javax.swing.JButton();
        markLessonAsCompletedButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));

        lessonsTable.setBackground(new java.awt.Color(230, 240, 250));
        lessonsTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lessonsTable.setForeground(new java.awt.Color(0, 30, 80));
        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Content", "Completed", "Resources"
            }
        ));
        jScrollPane1.setViewportView(lessonsTable);

        returnToMenuButton.setBackground(new java.awt.Color(230, 240, 250));
        returnToMenuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        returnToMenuButton.setForeground(new java.awt.Color(0, 30, 80));
        returnToMenuButton.setText("Return To Menu");
        returnToMenuButton.setFocusPainted(false);
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        markLessonAsCompletedButton.setBackground(new java.awt.Color(230, 240, 250));
        markLessonAsCompletedButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        markLessonAsCompletedButton.setForeground(new java.awt.Color(0, 30, 80));
        markLessonAsCompletedButton.setText("Mark Lesson As Completed");
        markLessonAsCompletedButton.setFocusPainted(false);
        markLessonAsCompletedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markLessonAsCompletedButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(252, 250, 247));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Details : Lessons");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(markLessonAsCompletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markLessonAsCompletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
        if (parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    private void markLessonAsCompletedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markLessonAsCompletedButtonActionPerformed

        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a lesson to mark as completed.",
                    "No Lesson Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String lessonId = lessonsTable.getValueAt(selectedRow, 1).toString(); // Lesson ID is in column 1
            String currentStatus = lessonsTable.getValueAt(selectedRow, 3).toString(); // Status is in column 3

            // Check if already completed
            if ("Yes".equals(currentStatus)) {
                JOptionPane.showMessageDialog(this,
                        "This lesson is already marked as completed!",
                        "Already Completed",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Lesson selectedLesson = null;
            for (Lesson lesson : course.getLessons()) {
                if (lesson.getLessonId().equals(lessonId)) {
                    selectedLesson = lesson;
                    break;
                }
            }

            if (selectedLesson == null) {
                JOptionPane.showMessageDialog(this,
                        "Could not find the selected lesson.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            authService = new AuthService();
            Student student = (Student) authService.getUserById(studentId);

            if (student == null) {
                JOptionPane.showMessageDialog(this,
                        "Could not find student information.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean success = studentService.completeLesson(student, course, selectedLesson);

            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Lesson marked as completed successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                loadLessonsToTable();

            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to mark lesson as completed. Please make sure you're enrolled in this course.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "An error occurred: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_markLessonAsCompletedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ViewCourseDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ViewCourseDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ViewCourseDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ViewCourseDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ViewCourseDetailsFrame().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JButton markLessonAsCompletedButton;
    private javax.swing.JButton returnToMenuButton;
    // End of variables declaration//GEN-END:variables
}
