/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Hajer1
 */
import model.*;
import service.*;

public class ViewCertificate extends javax.swing.JFrame {

    /**
     * Creates new form ViewCertificate
     */
    private String certificateId;
    private String studentId;
    private Certificate certificate;
    private MyCertificatesFrame parent;

    public ViewCertificate() {
        initComponents();
    }

    public ViewCertificate(String certificateId, String studentId, MyCertificatesFrame parent) {
        initComponents();
        this.certificateId = certificateId;
        this.studentId = studentId;
        this.parent = parent;
        this.certificate = getCertificate(certificateId);
        loadCertificateData();
    }

    //get certificate from its id
    public Certificate getCertificate(String certificateId) {
        try {
            CertificateService certService = new CertificateService();
            Certificate certificate = certService.getCertificateById(certificateId);
            return certificate;
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading certificate: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void loadCertificateData() {
        if (certificate != null) {
            // Set all the text fields with certificate data
            studentName.setText(certificate.getStudentName());
            courseName.setText(certificate.getCourseName());
            certificateIdBox.setText(certificate.getCertificateId());

            // Format the date nicely
            java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("MMMM dd, yyyy");
            String formattedDate = dateFormat.format(certificate.getIssueDate());
            issuedDate.setText(formattedDate);

            // Make all fields read-only since it's a certificate display
            studentName.setEditable(false);
            courseName.setEditable(false);
            certificateIdBox.setEditable(false);
            issuedDate.setEditable(false);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Certificate not found!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        returnToMenuButton = new javax.swing.JButton();
        CertificatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        courseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        certificateIdBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        issuedDate = new javax.swing.JTextField();
        downloadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(247, 250, 252));

        returnToMenuButton.setBackground(new java.awt.Color(230, 240, 250));
        returnToMenuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        returnToMenuButton.setForeground(new java.awt.Color(0, 30, 80));
        returnToMenuButton.setText("Return To Menu");
        returnToMenuButton.setFocusPainted(false);
        returnToMenuButton.setMinimumSize(new java.awt.Dimension(251, 32));
        returnToMenuButton.setPreferredSize(new java.awt.Dimension(251, 32));
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        CertificatePanel.setBackground(new java.awt.Color(255, 253, 240));
        CertificatePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 2, true));

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 50));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CERTIFICATE");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 50, 50));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OF COMPLETION");

        studentName.setBackground(new java.awt.Color(255, 253, 240));
        studentName.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        studentName.setForeground(new java.awt.Color(50, 50, 50));
        studentName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        courseName.setBackground(new java.awt.Color(255, 253, 240));
        courseName.setFont(new java.awt.Font("Garamond", 0, 24)); // NOI18N
        courseName.setForeground(new java.awt.Color(50, 50, 50));
        courseName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Has successfully completed");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel3.setText("Issued Date");

        certificateIdBox.setBackground(new java.awt.Color(255, 253, 240));
        certificateIdBox.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        certificateIdBox.setForeground(new java.awt.Color(50, 50, 50));
        certificateIdBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        certificateIdBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        certificateIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateIdBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jLabel5.setText("Certificate Id");

        issuedDate.setBackground(new java.awt.Color(255, 253, 240));
        issuedDate.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        issuedDate.setForeground(new java.awt.Color(50, 50, 50));
        issuedDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        issuedDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        issuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CertificatePanelLayout = new javax.swing.GroupLayout(CertificatePanel);
        CertificatePanel.setLayout(CertificatePanelLayout);
        CertificatePanelLayout.setHorizontalGroup(
            CertificatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CertificatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CertificatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CertificatePanelLayout.createSequentialGroup()
                        .addGroup(CertificatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CertificatePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(CertificatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CertificatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(CertificatePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(certificateIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        CertificatePanelLayout.setVerticalGroup(
            CertificatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CertificatePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(CertificatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(certificateIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(issuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        downloadButton.setBackground(new java.awt.Color(230, 240, 250));
        downloadButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        downloadButton.setForeground(new java.awt.Color(0, 30, 80));
        downloadButton.setText("Download");
        downloadButton.setFocusPainted(false);
        downloadButton.setMinimumSize(new java.awt.Dimension(251, 32));
        downloadButton.setPreferredSize(new java.awt.Dimension(251, 32));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(CertificatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CertificatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNameActionPerformed

    private void certificateIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateIdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateIdBoxActionPerformed

    private void issuedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedDateActionPerformed

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
        if (parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        String[] options = {"Download as Image", "Download as JSON", "Cancel"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this,
                "Choose download format:",
                "Download Certificate",
                javax.swing.JOptionPane.DEFAULT_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (choice == 0) {
            downloadAsImage();
        } else if (choice == 1) {
            downloadAsJSON();
        }
    }//GEN-LAST:event_downloadButtonActionPerformed
    private void downloadAsImage() {
        try {
            // Create image from the CertificatePanel only
            java.awt.image.BufferedImage image = new java.awt.image.BufferedImage(
                    CertificatePanel.getWidth(),
                    CertificatePanel.getHeight(),
                    java.awt.image.BufferedImage.TYPE_INT_RGB
            );

            java.awt.Graphics2D g2d = image.createGraphics();
            CertificatePanel.printAll(g2d); // Renders the certificate panel to image
            g2d.dispose();

            // Save as PNG
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File(
                    "Certificate_" + certificate.getCertificateId() + ".png"
            ));

            if (fileChooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
                javax.imageio.ImageIO.write(image, "PNG", fileChooser.getSelectedFile());
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Certificate image saved successfully!",
                        "Download Complete",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error saving image: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void downloadAsJSON() {
        try {
            if (certificate == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No certificate data to download!",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Create JSON content
            String jsonContent = String.format(
                    "{\n"
                    + "  \"certificateId\": \"%s\",\n"
                    + "  \"studentName\": \"%s\",\n"
                    + "  \"courseName\": \"%s\",\n"
                    + "  \"issueDate\": \"%s\",\n"
                    + "  \"studentId\": \"%s\",\n"
                    + "  \"courseId\": \"%s\"\n"
                    + "}",
                    certificate.getCertificateId(),
                    certificate.getStudentName(),
                    certificate.getCourseName(),
                    new java.text.SimpleDateFormat("yyyy-MM-dd").format(certificate.getIssueDate()),
                    certificate.getStudentId(),
                    certificate.getCourseId()
            );

            // Show file chooser to save the JSON file
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setSelectedFile(new java.io.File(
                    "Certificate_" + certificate.getCertificateId() + ".json"
            ));

            int result = fileChooser.showSaveDialog(this);
            if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File file = fileChooser.getSelectedFile();

                // Make sure it has .json extension
                if (!file.getName().toLowerCase().endsWith(".json")) {
                    file = new java.io.File(file.getAbsolutePath() + ".json");
                }

                // Write the JSON content to file
                java.io.FileWriter writer = new java.io.FileWriter(file);
                writer.write(jsonContent);
                writer.close();

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Certificate downloaded successfully!\n"
                        + "Saved as: " + file.getName(),
                        "Download Complete",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error downloading certificate: " + ex.getMessage(),
                    "Download Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCertificate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CertificatePanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField certificateIdBox;
    private javax.swing.JTextField courseName;
    private javax.swing.JButton downloadButton;
    private javax.swing.JTextField issuedDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton returnToMenuButton;
    private javax.swing.JTextField studentName;
    // End of variables declaration//GEN-END:variables
}
