/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.List;
import java.util.logging.Level;
import model.Course;
import service.CourseService;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariam
 */
public class AdminDashboardFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName());

    /**
     * Creates new form AdminDashboardFrame
     */
    private CourseService courseService;

    public AdminDashboardFrame() {
        initComponents();
        this.courseService = new CourseService();
        loadPendingCourses();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newCourses = new javax.swing.JTable();
        Accept = new javax.swing.JButton();
        reject = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setBackground(new java.awt.Color(192, 223, 253));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        newCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Title", "Course Description", "Instructor Id"
            }
        ));
        jScrollPane1.setViewportView(newCourses);
        if (newCourses.getColumnModel().getColumnCount() > 0) {
            newCourses.getColumnModel().getColumn(0).setResizable(false);
            newCourses.getColumnModel().getColumn(1).setResizable(false);
            newCourses.getColumnModel().getColumn(2).setResizable(false);
            newCourses.getColumnModel().getColumn(3).setResizable(false);
        }

        Accept.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Accept.setText("Accept Course");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        reject.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        reject.setText("Reject Course");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(165, Short.MAX_VALUE)
                                .addComponent(Accept)
                                .addGap(18, 18, 18)
                                .addComponent(reject)
                                .addGap(18, 18, 18)
                                .addComponent(Logout)))
                        .addGap(0, 165, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accept)
                    .addComponent(reject)
                    .addComponent(Logout))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = newCourses.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a course to reject.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = newCourses.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to reject course: " + courseId + "?",
                "Confirm Rejection",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = courseService.rejectCourse(courseId);
            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Course rejected successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                loadPendingCourses();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to reject course.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_rejectActionPerformed

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = newCourses.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a course to accept.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = newCourses.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to accept course: " + courseId + "?",
                "Confirm Approval",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = courseService.approveCourse(courseId);
            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Course approved successfully.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                loadPendingCourses();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to approve course.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AcceptActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to log out?",
                "Confirm Logout",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            new LoginFrame().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadPendingCourses() {
        try {
            List<Course> pendingCourses = courseService.getPendingCourses();

            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Course Id", "Course Title", "Course Description", "Instructor Id"}, 0
            );

            for (Course c : pendingCourses) {
                model.addRow(new Object[]{
                    c.getCourseId(),
                    c.getCourseTitle(),
                    c.getCourseDescription(),
                    c.getInstructorId()
                });
            }

            newCourses.setModel(model);

            // Optional: make columns not resizable
            if (newCourses.getColumnModel().getColumnCount() > 0) {
                for (int i = 0; i < newCourses.getColumnModel().getColumnCount(); i++) {
                    newCourses.getColumnModel().getColumn(i).setResizable(false);
                }
            }

        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error loading pending courses", ex);
            JOptionPane.showMessageDialog(this,
                    "Error loading pending courses.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboardFrame().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable newCourses;
    private javax.swing.JButton reject;
    // End of variables declaration//GEN-END:variables
}
