/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.List;
import model.Course;
import model.Student;
import service.*;
import db.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hajer1
 */
public class BrowseAllCoursesFrame extends javax.swing.JFrame {

    /**
     * Creates new form BrowseAllCoursesFrame
     */
    private StudentDashboardFrame parent;
    private String studentId;
    private StudentService studentService;
    private AuthService authService;
    private JsonDatabaseManager db;

    public BrowseAllCoursesFrame() {
        initComponents();
        initializeServices();
    }

    public BrowseAllCoursesFrame(String studentId, StudentDashboardFrame parent) {
        this.parent = parent;
        this.studentId = studentId;
        initComponents();
        initializeServices();
        loadCoursesToTable();
    }

    private void initializeServices() {
        this.studentService = new StudentService();
        this.authService = new AuthService();
        this.db = new JsonDatabaseManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        enrollInCourseButton = new javax.swing.JButton();
        returnToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));

        jLabel1.setBackground(new java.awt.Color(252, 250, 247));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Courses");

        coursesTable.setBackground(new java.awt.Color(230, 240, 250));
        coursesTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        coursesTable.setForeground(new java.awt.Color(0, 30, 80));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Description", "Lessons"
            }
        ));
        jScrollPane1.setViewportView(coursesTable);

        enrollInCourseButton.setBackground(new java.awt.Color(230, 240, 250));
        enrollInCourseButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        enrollInCourseButton.setForeground(new java.awt.Color(0, 30, 80));
        enrollInCourseButton.setText("Enroll In Course");
        enrollInCourseButton.setFocusPainted(false);
        enrollInCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollInCourseButtonActionPerformed(evt);
            }
        });

        returnToMenuButton.setBackground(new java.awt.Color(230, 240, 250));
        returnToMenuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        returnToMenuButton.setForeground(new java.awt.Color(0, 30, 80));
        returnToMenuButton.setText("Return To Menu");
        returnToMenuButton.setFocusPainted(false);
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollInCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enrollInCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollInCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollInCourseButtonActionPerformed
        int selectedRow = coursesTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a course to enroll in.",
                    "No Course Selected",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String courseId = (String) coursesTable.getValueAt(selectedRow, 0);
            String courseTitle = (String) coursesTable.getValueAt(selectedRow, 1);

            // Get student object
            Student student = (Student) authService.getUserById(studentId);
            Course course = studentService.browseAllCourses().stream()
                    .filter(c -> c.getCourseId().equals(courseId))
                    .findFirst()
                    .orElse(null);

            if (course == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Course not found!",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if already enrolled
            if (student.getEnrolledCourses().contains(courseId)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "You are already enrolled in this course!",
                        "Already Enrolled",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Enroll student
            boolean success = studentService.enrollInCourse(student, course);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Successfully enrolled in: " + courseTitle,
                        "Enrollment Successful",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                loadCoursesToTable();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Failed to enroll in course.",
                        "Enrollment Failed",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error enrolling in course: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_enrollInCourseButtonActionPerformed

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }

        // Show the parent dashboard and refresh courses
        if (parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowseAllCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowseAllCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowseAllCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowseAllCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowseAllCoursesFrame().setVisible(true);
            }
        });
    }

    public void loadCoursesToTable() {

        try {
            // Get course data from your service
            List<Course> allCourses = studentService.browseAllCourses();

            // Create table model and only show APPROVED courses
            String[] columns = {"ID", "Title", "Description", "Lessons"};
            DefaultTableModel model = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make table non-editable
                }
            };

            for (Course course : allCourses) {
                if (course != null && course.isApproved()) { // IMPORTANT: show approved only
                    Object[] row = new Object[]{
                        course.getCourseId(),
                        course.getCourseTitle(),
                        course.getCourseDescription(),
                        course.getLessons() != null ? course.getLessons().size() : 0
                    };
                    model.addRow(row);
                }
            }

            coursesTable.setModel(model);

            // Adjust column widths
            if (coursesTable.getColumnModel().getColumnCount() >= 4) {
                coursesTable.getColumnModel().getColumn(0).setPreferredWidth(60);  // ID
                coursesTable.getColumnModel().getColumn(1).setPreferredWidth(150); // Title
                coursesTable.getColumnModel().getColumn(2).setPreferredWidth(250); // Description
                coursesTable.getColumnModel().getColumn(3).setPreferredWidth(60);  // Lessons
            }

            System.out.println("Loaded " + model.getRowCount() + " approved courses.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading courses: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable coursesTable;
    private javax.swing.JButton enrollInCourseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnToMenuButton;
    // End of variables declaration//GEN-END:variables
}
