/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.List;
import model.*;
import service.*;

/**
 *
 * @author Hajer1
 */
public class ViewEnrolledCoursesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewEnrolledCoursesFrame
     */
    private String studentId;
    private StudentDashboardFrame parent;
    private StudentService studentService;
    private AuthService authService;
    private ViewCourseDetailsFrame courseDetails;

    public ViewEnrolledCoursesFrame() {
        initComponents();
        initializeServices();
    }

    public ViewEnrolledCoursesFrame(String studentId, StudentDashboardFrame parent) {
        initComponents();
        this.studentId = studentId;
        this.parent = parent;
        initializeServices();
        loadCoursesToTable();
    }
    // In constructor, add:

    private void initializeServices() {
        this.studentService = new StudentService();
        this.authService = new AuthService();
    }

    public String getCurrentStudentId() {
        return this.studentId;
    }

    public void loadCoursesToTable() {
        String currentStudentId = getCurrentStudentId();
        AuthService authService = new AuthService();
        User user = authService.getUserById(studentId);
        Student student = null;
        if (user instanceof Student) {
            student = (Student) user;
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "User is not a student or user not found!",
                    "Access Denied",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (currentStudentId == null) {
            System.out.println("No student ID available");
            return;
        }

        try {
            // Get course data from your service
            StudentService studentService = new StudentService();
            List<Course> studentCourses = studentService.getEnrolledCourses(student);

            // Create table data
            Object[][] data = new Object[studentCourses.size()][4];
            for (int i = 0; i < studentCourses.size(); i++) {
                Course course = studentCourses.get(i);
                data[i][0] = course.getCourseId();
                data[i][1] = course.getCourseTitle();
                data[i][2] = course.getCourseDescription();
                data[i][3] = course.getLessons() != null ? course.getLessons().size() : 0; // Handle null lessons
            }

            // Column names
            String[] columns = {"ID", "Title", "Description", "Lessons"};

            // Create table model and set it
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, columns) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // Make table non-editable
                }
            };
            coursesTable.setModel(model);

            // Adjust column widths
            coursesTable.getColumnModel().getColumn(0).setPreferredWidth(60);  // ID
            coursesTable.getColumnModel().getColumn(1).setPreferredWidth(150); // Title
            coursesTable.getColumnModel().getColumn(2).setPreferredWidth(250); // Description
            coursesTable.getColumnModel().getColumn(3).setPreferredWidth(60);  // Lessons

            System.out.println("Loaded " + studentCourses.size() + " courses for student: " + studentId);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading courses: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        viewCourseDetailsButton = new javax.swing.JButton();
        returnToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));

        jLabel1.setBackground(new java.awt.Color(252, 250, 247));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enrolled Courses");

        coursesTable.setBackground(new java.awt.Color(230, 240, 250));
        coursesTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        coursesTable.setForeground(new java.awt.Color(0, 30, 80));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Description", "Lessons"
            }
        ));
        jScrollPane1.setViewportView(coursesTable);

        viewCourseDetailsButton.setBackground(new java.awt.Color(230, 240, 250));
        viewCourseDetailsButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        viewCourseDetailsButton.setForeground(new java.awt.Color(0, 30, 80));
        viewCourseDetailsButton.setText("View Course Details");
        viewCourseDetailsButton.setFocusPainted(false);
        viewCourseDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCourseDetailsButtonActionPerformed(evt);
            }
        });

        returnToMenuButton.setBackground(new java.awt.Color(230, 240, 250));
        returnToMenuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        returnToMenuButton.setForeground(new java.awt.Color(0, 30, 80));
        returnToMenuButton.setText("Return To Menu");
        returnToMenuButton.setFocusPainted(false);
        returnToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCourseDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(returnToMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewCourseDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCourseDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCourseDetailsButtonActionPerformed

        int selectedRow = coursesTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a course to view details.",
                    "No Course Selected",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Get course information from the selected row
            String courseId = (String) coursesTable.getValueAt(selectedRow, 0);
            String courseTitle = (String) coursesTable.getValueAt(selectedRow, 1);
            String courseDescription = (String) coursesTable.getValueAt(selectedRow, 2);

            // You can also get the Course object if needed
            Course selectedCourse = null;
            List<Course> allCourses = studentService.browseAllCourses();
            for (Course course : allCourses) {
                if (course.getCourseId().equals(courseId)) {
                    selectedCourse = course;
                    break;
                }
            }

            if (selectedCourse == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Course not found!",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Open the course details frame with the selected course
            ViewCourseDetailsFrame viewCourse = new ViewCourseDetailsFrame(studentId, selectedCourse, this);
            viewCourse.setVisible(true);
            this.setVisible(false);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error opening course details: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewCourseDetailsButtonActionPerformed

    private void returnToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMenuButtonActionPerformed
        // TODO add your handling code here:
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }

        // Show the parent dashboard and refresh courses
        if (parent != null) {
            parent.setVisible(true);
        }

    }//GEN-LAST:event_returnToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEnrolledCoursesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnToMenuButton;
    private javax.swing.JButton viewCourseDetailsButton;
    // End of variables declaration//GEN-END:variables
}
